Aula8/Models/Projeto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Aula8.Models
{
    public class Projeto
    {
        public int Id { get; set; }


        public string NomeDoProjeto { get; set; }
        public string DescrisaoDoProjeto { get; set; }
        public DateTime DataDeInicioDoProjeto { get; set; }
        public DateTime DataDeTerminoDoProjeto { get; set; }
        public string EstadoDoProjeto { get; set; }
        public virtual List<Usuario> Usuarios { get; set; }
    }
}

Aula8/Controllers/ProjetoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aula8.DAL;
using Aula8.Models;

namespace Aula8.Controllers
{
    public class ProjetoController : Controller
    {
        private GerenciamentoDeProjetosContext db = new GerenciamentoDeProjetosContext();
        public int? idProjeto;
        public Projeto projetoAuxiliar;

        // GET: Projeto
        public ActionResult Index()
        {
            return View(db.Projeto.ToList());
        }

        // GET: Projeto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projeto.Find(id);
            List<int> usuariosId = db.ObterUsuariosDoProjeto(projeto.Id);
            foreach (int idusuario in usuariosId)
            {
                projeto.Usuarios.Add(db.Usuario.Find(idusuario));
            }
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }
        public ActionResult AdicionarParticipanteAoProjeto(int? id,int? idProjeto)
        {
            db.InserirEmProjetoUsuariosPorId(idProjeto, id);
            db.SaveChanges();
            return View();
        }

        public ActionResult AdicionarParticipantesDoProjeto(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projeto.Find(id);

            idProjeto = projeto.Id;
            projetoAuxiliar = new Projeto();
            projetoAuxiliar.Id = projeto.Id;

            List<Usuario> TodosOsUsuarios = db.Usuario.ToList();
            List<Usuario> usuarios = new List<Usuario>();

            List<int> usuariosId = db.ObterUsuariosDoProjeto(projeto.Id);

            foreach (int idusuario in usuariosId)
            {
                usuarios.Add(db.Usuario.Find(idusuario));
                
            }
            
            var listaDeUsuarios = TodosOsUsuarios.Except(projeto.Usuarios).ToList();
            foreach (Usuario usu in listaDeUsuarios) 
            {
                usu.Projetos.Add(projeto);
            }
            
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(listaDeUsuarios);
        }
        public ActionResult AlterarParticipantesDoProjeto(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Usuario> usuarios = new List<Usuario>();

            Projeto projeto = db.Projeto.Find(id);
            List<int> usuariosId = db.ObterUsuariosDoProjeto(projeto.Id);
            foreach (int idusuario in usuariosId)
            {
                usuarios.Add(db.Usuario.Find(idusuario));
            }
            projeto.Usuarios = usuarios.Distinct().ToList();
            foreach (Usuario usu in projeto.Usuarios)
            {
                usu.Projetos.Add(projeto);
            }
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto.Usuarios);
        }


        public ActionResult ParticipantesDoProjeto(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Usuario> usuarios = new List<Usuario>();

            Projeto projeto = db.Projeto.Find(id);
            List<int> usuariosId = db.ObterUsuariosDoProjeto(projeto.Id);
            foreach (int idusuario in usuariosId)
            {
                usuarios.Add(db.Usuario.Find(idusuario));
            }
            projeto.Usuarios = usuarios.Distinct().ToList();
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto.Usuarios);
        }
        public ActionResult ExcluirParticipanteDoProjeto(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        public ActionResult ExcluirParticipanteComSucesso(int? id, int? idProjeto)
        {
            db.DeletarEmProjetoUsuariosPorId(idProjeto,id);
            db.SaveChanges();
            return View();
        }

        // GET: Projeto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projeto/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NomeDoProjeto,DescrisaoDoProjeto,DataDeInicioDoProjeto,DataDeTerminoDoProjeto,EstadoDoProjeto")] Projeto projeto)
        {
            if (ModelState.IsValid)
            {
                db.Projeto.Add(projeto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projeto);
        }

        // GET: Projeto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projeto.Find(id);
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }

        // POST: Projeto/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NomeDoProjeto,DescrisaoDoProjeto,DataDeInicioDoProjeto,DataDeTerminoDoProjeto,EstadoDoProjeto")] Projeto projeto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projeto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projeto);
        }

        // GET: Projeto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projeto.Find(id);
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }

        // POST: Projeto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Projeto projeto = db.Projeto.Find(id);
            db.Projeto.Remove(projeto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aula8/Controllers/TarefaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aula8.DAL;
using Aula8.Models;

namespace Aula8.Controllers
{
    public class TarefaController : Controller
    {
        private GerenciamentoDeProjetosContext db = new GerenciamentoDeProjetosContext();

        // GET: Tarefa
        public ActionResult Index()
        {
            return View(db.Tarefa.ToList());
        }

        // GET: Tarefa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefa tarefa = db.Tarefa.Find(id);
            if (tarefa == null)
            {
                return HttpNotFound();
            }
            return View(tarefa);
        }

        public ActionResult AdicionadoComSucesso(Tarefa tarefa)
        {
            db.Tarefa.Add(tarefa);
            db.SaveChanges();
            return View(tarefa);
        }

        // GET: Tarefa/Create
        public ActionResult Adicionar(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Tarefa/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NomeDaTarefa,DescrisaoDaTarefa,StatusDaTarefa,TempoParaRealizacaoDaTarefa,DataDeInicioDaTarefa,DataDeTerminoDaTarefa,ProjetoAssociado")] Tarefa tarefa)
        {
            db.Tarefa.Add(tarefa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Tarefa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefa tarefa = db.Tarefa.Find(id);
            if (tarefa == null)
            {
                return HttpNotFound();
            }
            return View(tarefa);
        }

        // POST: Tarefa/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NomeDaTarefa,DescrisaoDaTarefa,StatusDaTarefa,TempoParaRealizacaoDaTarefa,DataDeInicioDaTarefa,DataDeTerminoDaTarefa")] Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tarefa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tarefa);
        }

        // GET: Tarefa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefa tarefa = db.Tarefa.Find(id);
            if (tarefa == null)
            {
                return HttpNotFound();
            }
            return View(tarefa);
        }

        // POST: Tarefa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tarefa tarefa = db.Tarefa.Find(id);
            db.Tarefa.Remove(tarefa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aula8/Views/Projeto/AdicionarParticipanteAoProjeto.cshtml
@model Aula8.Models.Usuario

@{
    ViewBag.Title = "AdicionarParticipanteAoProjeto";
}

<h2>Participante Adicionado com Sucesso!</h2>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Aula8/Views/Projeto/AdicionarParticipantesDoProjeto.cshtml
@model IEnumerable<Aula8.Models.Usuario>

@{
    ViewBag.Title = "AdicionarParticipantesDoProjeto";
}

<h2>AdicionarParticipantesDoProjeto</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cargo)
        </th>
        <th></th>
    </tr>
    @{
        int? idProjeto = 0;
        foreach (var item in Model)
        {
            foreach (var projeto in item.Projetos)
            {
                    idProjeto = projeto.Id;
            }
        }
    }


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo)
            </td>
            <td>
                @Html.ActionLink("Adicionar", "AdicionarParticipanteAoProjeto", new { id = item.Id, idProjeto = idProjeto })
            </td>
        </tr>
    }

</table>

Aula8/Views/Projeto/AlterarParticipantesDoProjeto.cshtml
@model IEnumerable<Aula8.Models.Usuario>

@{
    ViewBag.Title = "AlterarParticipantesDoProjeto";
}

<h2>AlterarParticipantesDoProjeto</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cargo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cargo)
        </td>
        <td>
            @Html.ActionLink("Delete", "ExcluirParticipanteDoProjeto", new { id = item.Id })
        </td>
    </tr>
}

</table>

Aula8/Views/Projeto/Create.cshtml
@model Aula8.Models.Projeto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Projeto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeDoProjeto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescrisaoDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescrisaoDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescrisaoDoProjeto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeInicioDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeInicioDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeInicioDoProjeto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeTerminoDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeTerminoDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeTerminoDoProjeto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoDoProjeto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aula8/Views/Projeto/Delete.cshtml
@model Aula8.Models.Projeto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Projeto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescrisaoDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescrisaoDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeInicioDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeInicioDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeTerminoDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeTerminoDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoDoProjeto)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Aula8/Views/Projeto/Details.cshtml
@model Aula8.Models.Projeto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Projeto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescrisaoDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescrisaoDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeInicioDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeInicioDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeTerminoDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeTerminoDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoDoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoDoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuarios)
        </dt>

        <dd>
            @Html.ActionLink("Ver Participantes do Projeto", "ParticipantesDoProjeto", new { id = Model.Id})
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Aula8/Views/Projeto/Edit.cshtml
@model Aula8.Models.Projeto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Projeto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.NomeDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeDoProjeto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DescrisaoDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DescrisaoDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DescrisaoDoProjeto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataDeInicioDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataDeInicioDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataDeInicioDoProjeto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataDeTerminoDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataDeTerminoDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataDeTerminoDoProjeto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EstadoDoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EstadoDoProjeto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EstadoDoProjeto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <dt>
            @Html.DisplayNameFor(model => model.Usuarios)
        </dt>

        <dd>
            @Html.ActionLink("Excluir Participantes do Projeto", "AlterarParticipantesDoProjeto", new { id = Model.Id })
        </dd>

        <dd>
            @Html.ActionLink("Adicionar Participantes no Projeto", "AdicionarParticipantesDoProjeto", new { id = Model.Id })
        </dd>
    </div>

    <div class="form-group">
        <dt>
            Tarefas
        </dt>

        <dd>
            @Html.ActionLink("Excluir Tarefas no Projeto", "ExcluirTarefaDoProjeto", new { id = Model.Id })
        </dd>

        <dd>
            @Html.ActionLink("Adicionar Tarefas no Projeto", "Adicionar","Tarefa", new { id = Model.Id },null)
        </dd>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aula8/Views/Projeto/ExcluirParticipanteComSucesso.cshtml
@model Aula8.Models.Usuario

@{
    ViewBag.Title = "ExcluirParticipanteComSucesso";
}

<h2>Participante já está fora do Projeto</h2>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Aula8/Views/Projeto/ExcluirParticipanteDoProjeto.cshtml
@model Aula8.Models.Usuario

@{
    ViewBag.Title = "ExcluirParticipanteDoProjeto";
}

<h2>Excluir Participante Do Projeto</h2>

<h3>Voce tem certeza que deseja excluir esse Participante?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargo)
        </dd>

    </dl>
    @{
        int? idProjeto = 0;
        foreach (var item in Model.Projetos)
        {
            idProjeto = item.Id;
        }
        <h1>@Model.Id</h1>
        <h1>@idProjeto</h1>
    }
    <div class="form-actions no-color">
        @Html.ActionLink("Deletar", "ExcluirParticipanteComSucesso", new { id = Model.Id, idProjeto = idProjeto })
    </div>
</div>

Aula8/Views/Projeto/Index.cshtml
@model IEnumerable<Aula8.Models.Projeto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomeDoProjeto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescrisaoDoProjeto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataDeInicioDoProjeto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataDeTerminoDoProjeto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoDoProjeto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomeDoProjeto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DescrisaoDoProjeto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataDeInicioDoProjeto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataDeTerminoDoProjeto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoDoProjeto)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Aula8/Views/Projeto/ParticipantesDoProjeto.cshtml
@model IEnumerable<Aula8.Models.Usuario>

@{
    ViewBag.Title = "ParticipantesDoProjeto";
}

<h2>ParticipantesDoProjeto</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cargo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo)
            </td>
            <td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>